"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductsCategoriesRoutes = exports.RolesRoutes = exports.ServicesProvidersRoutes = exports.ServicesRoutes = exports.EmployeesRoutes = exports.ServicesPricesRoutes = exports.RecieversRoutes = exports.CustomersRoutes = exports.AgenciesRoutes = void 0;
const AgenciesRoutes_1 = __importDefault(require("./AgenciesRoutes"));
exports.AgenciesRoutes = AgenciesRoutes_1.default;
const CustomersRoutes_1 = __importDefault(require("./CustomersRoutes"));
exports.CustomersRoutes = CustomersRoutes_1.default;
const RecieversRoutes_1 = __importDefault(require("./RecieversRoutes"));
exports.RecieversRoutes = RecieversRoutes_1.default;
const EmployeesRoutes_1 = __importDefault(require("./EmployeesRoutes"));
exports.EmployeesRoutes = EmployeesRoutes_1.default;
const ServicesRoutes_1 = __importDefault(require("./ServicesRoutes"));
exports.ServicesRoutes = ServicesRoutes_1.default;
const ServicesProvidersRoutes_1 = __importDefault(require("./ServicesProvidersRoutes"));
exports.ServicesProvidersRoutes = ServicesProvidersRoutes_1.default;
const ServicesPricesRoutes_1 = __importDefault(require("./ServicesPricesRoutes"));
exports.ServicesPricesRoutes = ServicesPricesRoutes_1.default;
const RolesRoutes_1 = __importDefault(require("./RolesRoutes"));
exports.RolesRoutes = RolesRoutes_1.default;
const ProductsCategoriesRoutes_1 = __importDefault(require("./ProductsCategoriesRoutes"));
exports.ProductsCategoriesRoutes = ProductsCategoriesRoutes_1.default;
